name: Prédiction de Cancer Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train Model
      run: python bcancer.py
      uses: actions/upload-artifact@v3
      with:
          name: breast_cancer_model
          path: breast_cancer_model.pkl

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name:  Download math result for avant
      uses: actions/download-artifact@v3
        with:
          name: breast_cancer_model

    - name: Test Model
      run: python test.py